name: AWS BUILD&DEPLOY
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - run: sed s/arm64/x86_64/g template.yaml > template_github_actions.yaml
      - run: sam build --use-container -t template_github_actions.yaml --debug --config-file samconfig_github_actions.toml
      - run: sam deploy
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --config-file samconfig_github_actions.toml
          --s3-bucket ${{ secrets.S3_BUCKET_NAME }}
          --parameter-overrides
          FirebaseClientEmail=${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FirebasePrivateKey=${{ secrets.FIREBASE_PRIVATE_KEY }}
          FirebaseProjectId=${{ secrets.FIREBASE_PROJECT_ID }}
          LineChannelAccessToken=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LineChannelSecret=${{ secrets.LINE_CHANNEL_SECRET }}
          WhereAreYouLocationUrl=${{ secrets.WHEREAREYOU_LOCATION_URL }}
          WhereAreYouUrlToken=${{ secrets.WHEREAREYOU_URL_TOKEN }}
